### PR TITLE
add descriptions to bundled tutorials; document use

### PR DESCRIPTION
**Pull request by kevinushey**
Closes https://github.com/rstudio/learnr/issues/312.

### CODE REVIEW

**Comment by kevinushey** [comment]
Here's the current treatment I have for this PR:

Screen Shot 2019-12-18 at 1 21 44 PM

I'd like to propose (if this PR is accepted) that new tutorials should have a short one-paragraph description going forward.

I'd also like to propose the use of an `internal` field to indicate tutorials that might not want to be exposed / indexed by front-ends (ie, they exist just as example tutorials for developers)

**Comment by schloerke** [comment]
Do you think we could use `private` instead of `internal`?

Reminds me of https://docs.npmjs.com/files/package.json#private

**Comment by kevinushey** [comment]
Sounds good to me!

**Comment by schloerke** [comment]
@kevinushey 

Would you like this information (and possibly the whole yaml header information) to be supplied in `learnr::available_tutorials()`? 

Is there a way we can move the template from within RStudio to within learnr? So as more information becomes available, the display is tied to learnr itself.  ... Is this a wrong approach?

**Comment by kevinushey** [comment]
> Would you like this information (and possibly the whole yaml header information) to be supplied in learnr::available_tutorials()?

Yes, that would be useful.

> Is there a way we can move the template from within RStudio to within learnr? So as more information becomes available, the display is tied to learnr itself. ... Is this a wrong approach?

The main reason I decided to implement this first in RStudio is I wanted to make sure the generated HTML could be easily styled to accommodate both light + dark RStudio themes. I'd be open to having a solution in `learnr`, though.

**Comment by schloerke** [comment]
With the same logic... I'm going to not display the `private: true` tutorials in `available_tutorials()`

**Pull request merged**
