### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by kuba58426**
Added Polish translation

### CODE REVIEW

**Review by gadenbuie — DISMISSED** [review]
Thank you @kuba58426!

**Comment by gadenbuie** [comment]
Actually, @kuba58426 would you like to add a few encouraging and praising phrases in Polish to [data-raw/i18n_random-phrases.yml](https://github.com/kuba58426/learnr/blob/pl_translation/data-raw/i18n_random-phrases.yml)?

**Comment by kuba58426** [comment]
> Actually, @kuba58426 would you like to add a few encouraging and praising phrases in Polish to [data-raw/i18n_random-phrases.yml](https://github.com/kuba58426/learnr/blob/pl_translation/data-raw/i18n_random-phrases.yml)?

Yes, I will do it tomorrow, no problem. Could I ask you to use my full name in the contributors section? It's Jakub Jędrusiak.

**Comment by kuba58426** [comment]
@gadenbuie Done.

**Review by gadenbuie — APPROVED** [review]
@kuba58426 Thanks for submitting the random praise/encouragement and thanks again for the translation!

**Pull request merged**
