### PR TITLE
Update the translations - add pt-BR (Brazilian Portuguese)

### PR DESCRIPTION
**Pull request by beatrizmilz**
Hi @gadenbuie ! I'm sending a new version of #475!

(I did not add anything in the news files... only updated the yml file for the translation..)

### CODE REVIEW

**Comment by gadenbuie** [comment]
Thank you @beatrizmilz! For compatibility with bootbox, I'd like to change the language key to `pt`. Do you know if the translation would differ for `pt-PT` (Portuguese as spoken in Portugal)?

**Comment by beatrizmilz** [comment]
Thank you @gadenbuie ! About the differences between Portuguese from Portugal and Brazil, I'm not sure. I think it would be good if someone could review it. 

Hi @DanielAlvesLABDH , do you know anyone that would be interested to review the language in this PR? Thank you!

**Comment by DanielAlvesLABDH** [comment]
Hi @beatrizmilz , I think the Portuguese used is correct. Didn't found any mistakes and the differences for pt-PT are minor and not relevant

**Comment by gadenbuie** [comment]
Thank you @beatrizmilz and @DanielAlvesLABDH. I'm excited that learnr can now speak Portuguese!

**Comment by gadenbuie** [comment]
@beatrizmilz @DanielAlvesLABDH Eu deveria ter dito: Estou animado que agora learnr pode falar Português!

**Comment by beatrizmilz** [comment]
Thank you both @gadenbuie and @DanielAlvesLABDH !

Também estou animada que agora podemos criar tutoriais em Português :D

**Pull request merged**
