### PR TITLE
Require markdown >= 1.3 and update usage

### PR DESCRIPTION
**Pull request by yihui**
This function will be removed in a future version of **markdown**.

I'll let you know when this PR is ready to merge. Thanks!

PR task list:
- [x] Update NEWS
- [ ] Add tests (if possible)
- [x] Update documentation with `devtools::document()`

### CODE REVIEW

**Comment by gadenbuie** [comment]
Thanks @yihui, is this ready for review?

**Comment by yihui** [comment]
I just made a new release of the **markdown** package to CRAN the other day. This PR is ready to merge now (after it passes the checks). Thanks!

**Comment by gadenbuie** [comment]
@yihui First, I really appreciate the complete PR and for making the transition easy! That said, I'm looking at learnr's single use of `markdown::mark_html()` and wondering if it would make more sense for us to also switch to calling commonmark directly. Are there advantages to using the markdown package that we'd miss or have to handle if we switched to commonmark?

**Comment by yihui** [comment]
Good question. The **commonmark** package is basically a bare minimal version of Markdown, and the **markdown** package supports a few extra features such as LaTeX math, base64 encoding images, super/subscripts, etc. If you don't need these extra features, you can definitely just call `commonmark::markdown_html()`.

**Review by gadenbuie — APPROVED** [review]
Thanks again @yihui! And thank you for clarifying – we'll stick with {markdown} for now.

**Pull request merged**
